service: minesweeper-api

frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: ${opt:profile}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  stackName: MinesweeperApi-${self:custom.stageCapitalized}
  apiName: MinesweeperApi-${self:custom.stageCapitalized}
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: serverless-deployment-repository
    maxPreviousDeploymentArtifacts: 10
  deploymentPrefix: minesweeper
  timeout: 29
  httpApi:
    cors: true
  environment:
    STAGE: ${self:provider.stage}

custom:
  serverless-offline:
    httpPort: ${opt:port, '4000'}
  customDomain:
    http:
      domainName: api.mine-sweeper.org
      stage: ${self:provider.stage}
      createRoute53Record: true
      endpointType: 'regional'
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    excludeFiles: src/**/*.spec.ts
  stages:
    dev: Dev
    stage: Stage
    prod: Prod
  stageCapitalized: ${self:custom.stages.${self:provider.stage}}

package:
  individually: false
  exclude:
    - ./node_modules/**
    - node_modules/**
  include:
    - src/**
    - package.json
  excludeDevDependencies: true

functions:
  applications:
    handler: src/handler.expressHandler
    events:
      - httpApi:
          path: /{proxy+}
          method: any